import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const syFont = localFont({
  src: "../../font/SourceHanSansSC-VF.otf.woff2",
  weight: "Regular",
  style: "normal",
  display: "swap",
});

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={`${syFont.className} antialiased`}>{children}</body>
    </html>
  );
}
